name: CI - Python Tests

# Trigger the workflow on pushes and pull requests involving Python files
on:
  workflow_dispatch:
  push:
    paths:
      - 'src/**'      # Monitor changes in src directory
      - 'include/**'  # Monitor changes in include directory
  pull_request:
    paths:
      - 'src/**'
      - 'include/**'

jobs:
  python-tests:
    runs-on: ubuntu-latest  # Use the latest Ubuntu virtual environment

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Specify the Python version you need

      - name: Install project and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .  # Install the project from the root directory

      - name: Run Python unit tests
        run: |
          python ../tests/unit_tests/py_spline_tests.py