name: CI - Build and Test

# Trigger the workflow on pushes and pull requests
on:
  push:
    paths:
      - 'src/**'      # Monitor changes in src directory
      - 'include/**'  # Monitor changes in include directory
  pull_request:
    paths:
      - 'src/**'
      - 'include/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest  # Use the latest Ubuntu virtual environment

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Install CMake and dependencies
      - name: Install CMake and g++
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++  # Ensure CMake and g++ are installed

      # Step 3: Build and run tests
      - name: Build and run tests
        run: |
          mkdir build
          cd build
          cmake -DBUILD_TESTING=ON ..
          make
          ctest --output-on-failure  # Runs tests with detailed output if they fail
