name: CI - Build and Test

# Trigger the workflow on pushes and pull requests
on:
  workflow_dispatch:
  push:
    paths:
      - 'src/**'      # Monitor changes in src directory
      - 'include/**'  # Monitor changes in include directory
  pull_request:
    paths:
      - 'src/**'
      - 'include/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest  # Use the latest Ubuntu virtual environment

    steps:
      - uses: actions/checkout@v3
    
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential g++

      - name: Build and run tests
        run: |
          mkdir build
          cd build
          cmake -DENABLE_TESTS=ON ..
          make
          ctest --output-on-failure  # Runs tests with detailed output if they fail
