name: CI - Build and Test

# Trigger the workflow on pushes and pull requests
on:
  push:
    paths:
      - 'src/**'      # Monitor changes in src directory
      - 'include/**'  # Monitor changes in include directory
  pull_request:
    paths:
      - 'src/**'
      - 'include/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest  # Use the latest Ubuntu virtual environment

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up CMake
      - name: Set up CMake
        uses: cmake/setup-cmake@v1  # Correct action for setting up CMake
        with:
          cmake-version: '3.20.2'  # Specify the CMake version you need

      # Step 3: Install dependencies (customize as needed)
      - name: Install dependencies
        run: sudo apt-get install -y g++ # CMake is already installed by the previous step

      # Step 4: Build and run tests
      - name: Build and run tests
        run: |
          mkdir build
          cd build
          cmake -DBUILD_TESTING=ON ..
          make
          ctest --output-on-failure  # Runs tests with detailed output if they fail